version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - minio

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=jinalgajjar
      - MINIO_ROOT_PASSWORD=jinalgajjar 
    ports:
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    command: server --console-address ":9001" data
